### ISSUE TITLE
Feature: Submit a Poll Response

### ISSUE THREAD

**Issue by easybulb** [easybulb/love-running#1]
In order to **provide my opinion with regards to certain running topic or event** as a **user**, I can **select and submit an answer from the poll**

## Acceptance Criteria:

* The option should be provided as a checkbox
* The checkbox should be “checked” by default
* The option should appear next to the submit button
* After submitting the default submission confirmation should be adjusted to include the user name.

## Tasks
- [ ] Update the view: the poll design (HTML and CSS) to include the check-box and to show the name of the submitter
- [ ] Create a new field in the modal to track the username
- [ ] Update the controller function
- [ ] Update unit test scripts
- [ ] Test the functionality
