### ISSUE TITLE
Feature: Pick Expiry Date in Poll

### ISSUE THREAD

**Issue by easybulb** [easybulb/love-running#2]
In order to **automatically hide the poll** as an **administrator**, I can **pick the expiry date while publishing a poll**

## Acceptance Criteria:

* The poll should disappear at 11:59PM on the target date.
* The real estate of the "Poll" should be reserved on the home page. A message that says "Stay tuned, a new poll is coming soon" should appear if no other poll is active.
* The administrator expiry date should be at least three days after the current date.

## Tasks
- [ ] Update the admin module view: the poll design (HTML and CSS) to include date picker.
- [ ] Update the admin module view: show, "Stay tuned, a new poll is coming soon".
- [ ] Create a JavaScript function to validate the expiry date is at least after 3 days.
- [ ] Create a job to check expired polls everyday at 11:59PM and Hide them.
- [ ] Update the controller function
- [ ] Update the unit text scripts
- [ ] Test the functionality
